In [1]:
!python3 -m pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd
data = pd.read_csv("products.csv")

In [3]:
data.head(3)

  product_category                                        description
0      Electronics  Fluxon gaming console (Pro) with fast charging...
1      Electronics  Fluxon laptop (SE) with expandable storage, no...
2      Electronics  Acme gaming console (Lite) with expandable sto...

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  1000 non-null   str
 1   description       1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [5]:
data.shape

(1000, 2)

In [6]:
data.columns

Index(['product_category', 'description'], dtype='str')

In [7]:
data.nunique

<bound method DataFrame.nunique of     product_category                                        description
0        Electronics  Fluxon gaming console (Pro) with fast charging...
1        Electronics  Fluxon laptop (SE) with expandable storage, no...
2        Electronics  Acme gaming console (Lite) with expandable sto...
3           Clothing  Nova women's shorts, formal style in black, de...
4        Electronics  ByteLabs gaming console (Lite) with expandable...
..               ...                                                ...
995         Clothing  ByteLabs unisex leggings, office‑ready style i...
996      Electronics  ZenCo camera (SE) with face unlock, water‑resi...
997      Electronics  ByteLabs headphones (2024 model) with water‑re...
998         Clothing  Lumina women's jeans, streetwear style in beig...
999         Clothing  Orion kids shorts, office‑ready style in green...

[1000 rows x 2 columns]>

In [8]:
!python3 -m pip install spacy

Requirement already satisfied: spacy in ./venv/lib/python3.11/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./venv/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./venv/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./venv/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./venv/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./venv/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in ./venv/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./venv/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in ./venv/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./venv/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in ./venv/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in ./venv/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./venv/lib/python3.11/site-packages (from spacy) (0.26.8)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./venv/lib/python3.11/site-packages (from spacy) (4.68.4)
Requirement already satisfied: numpy>=1.19.0 in ./venv/lib/python3.11/site-packages (from spacy) (2.4.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in ./venv/lib/python3.11/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in ./venv/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./venv/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in ./venv/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./venv/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./venv/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in ./venv/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in ./venv/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.0)
Requirement already satisfied: httpx>=0.24.0 in ./venv/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in ./venv/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.2)
Requirement already satisfied: httpcore==1.* in ./venv/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./venv/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./venv/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in ./venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in ./venv/lib/python3.11/site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [9]:
import spacy

In [10]:
!python3 -m pip install click

Requirement already satisfied: click in ./venv/lib/python3.11/site-packages (8.4.2)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [11]:
import spacy

In [12]:
!python3 -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 32.7 MB/s  0:00:10:00:0100:01

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [13]:
nlp = spacy.load("en_core_web_lg")

In [14]:
data.head(3)

  product_category                                        description
0      Electronics  Fluxon gaming console (Pro) with fast charging...
1      Electronics  Fluxon laptop (SE) with expandable storage, no...
2      Electronics  Acme gaming console (Lite) with expandable sto...

In [15]:
X = data['description']
Y = data['product_category']

In [16]:
X.info()

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: description
Non-Null Count  Dtype
--------------  -----
1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB

In [17]:
Y.info()

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: product_category
Non-Null Count  Dtype
--------------  -----
1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB

In [18]:
type(X)

pandas.Series

In [19]:
type(Y)

pandas.Series

In [20]:
def lemmatize(text):
    doc = nlp(text)
    lemma_text = [token.lemma_.lower() for token in doc]
    return " ".join(lemma_text)

In [21]:
x_data = X.apply(lemmatize).astype("string")

In [22]:
x_data

0      fluxon gaming console ( pro ) with fast chargi...
1      fluxon laptop ( se ) with expandable storage ,...
2      acme gaming console ( lite ) with expandable s...
3      nova woman 's short , formal style in black , ...
4      bytelabs gaming console ( lite ) with expandab...
                             ...
995    bytelabs unisex legging , office‑ready style i...
996    zenco camera ( se ) with face unlock , water‑r...
997    bytelabs headphone ( 2024 model ) with water‑r...
998    lumina woman 's jean , streetwear style in bei...
999    orion kid short , office‑ready style in green ...
Name: description, Length: 1000, dtype: string

In [23]:
STOP_WORDS  = nlp.Defaults.stop_words
print (STOP_WORDS)

{'may', 'should', 'thereafter', 'are', 'hereby', 'mostly', 'up', 'just', 'some', 'why', 'beforehand', 'thereby', 'do', 'so', 'whatever', 'those', 'fifteen', 'than', 'something', 'also', 'much', 'everything', 'latter', 'in', 'how', 'no', 'here', '‘ll', 'somehow', 'over', 'toward', 'besides', 'keep', 'eight', 'perhaps', 'at', 'then', '’ll', 'less', 'hereupon', 'once', 'each', 'still', 'off', 'below', 're', 'above', 'without', 'take', '‘re', 'but', 'anyhow', 'seems', 'several', 'upon', 'whither', 'via', 'meanwhile', 'third', 'its', 'almost', 'such', 'namely', 'top', '’d', 'hereafter', 'whereas', "n't", 'out', 'through', 'due', 'otherwise', 'nobody', 'ever', 'very', 'cannot', 'was', 'now', 'it', 'afterwards', 'get', 'three', 'from', 'his', 'again', 'himself', 'when', 'thereupon', 'throughout', 'anything', 'latterly', '’s', 'enough', 'along', 'two', 'around', 'somewhere', 'put', 'name', 'always', 'which', 'ourselves', '‘d', 'five', 'last', "'s", 'nowhere', 'of', 'since', 'nothing', 'they', 'thru', 'us', 'however', 'never', 'this', 'more', 'any', "'ve", 'not', 'move', 'while', 'who', 'side', 'yourself', 'alone', 'well', 'anyway', 'there', 'nine', 'further', 'next', 'rather', 'few', 'beyond', 'must', 'across', 'ten', 'an', 'sixty', 'only', 'twelve', 'been', 'too', 'regarding', 'give', 'seem', 'one', 'being', 'whoever', 'show', 'her', 'call', 'will', "'d", 'were', 'sometimes', '‘ve', 'that', "'ll", 'say', 'herself', 'many', 'own', 'whereupon', '’re', "'re", 'can', 'has', 'had', 'six', 'or', 'neither', 'as', 'could', 'towards', 'sometime', 'unless', 'thus', 'using', 'by', 'go', 'twenty', 'mine', 'my', 'she', 'itself', 'others', 'would', 'nevertheless', 'ca', 'does', 'indeed', 'whence', 'formerly', 'forty', '’ve', 'seemed', 'either', 'quite', 'full', 'most', 'back', 'yourselves', 'except', "'m", 'hence', 'least', 'the', 'see', 'same', 'against', 'whereafter', 'whom', 'else', 'whenever', 'under', 'where', '‘s', 'about', 'whether', 'with', 'these', 'a', 'wherein', 'became', 'four', 'within', 'for', 'anywhere', 'down', 'n‘t', 'anyone', 'former', 'yours', 'am', 'until', 'front', 'between', 'none', 'hundred', 'our', 'empty', 'part', 'often', 'doing', 'done', 'wherever', 'every', 'per', 'another', 'elsewhere', 'already', 'during', 'what', 'them', 'themselves', 'you', 'serious', 'myself', 'to', 'whose', 'various', 'behind', 'because', 'other', 'first', 'have', 'if', 'everywhere', 'becomes', 'n’t', 'someone', 'therein', 'fifty', 'on', 'he', 'become', 'becoming', 'herein', 'nor', 'make', 'your', 'be', 'me', 'ours', 'might', 'did', 'noone', 'even', 'both', 'everyone', 'i', 'moreover', 'used', 'their', 'before', 'amount', 'beside', 'together', 'into', 'yet', 'onto', 'eleven', 'after', 'really', 'please', '‘m', 'therefore', 'made', 'is', 'seeming', 'and', 'among', 'thence', 'hers', 'all', 'him', 'bottom', '’m', 'we', 'whereby', 'although', 'though', 'whole', 'amongst'}

In [24]:
SAFE_WORDS = {"no", "not", "nor"}
SAFE_STOPWORDS = set(STOP_WORDS) - SAFE_WORDS
def remove_stopwords_spacy(text: str) -> str:
    doc = nlp(str(text))
    tokens = [t.text for t in doc if t.is_alpha and t.text.lower() not in SAFE_STOPWORDS]  # <-- per-token check
    return " ".join(tokens)

In [25]:
x_data_new = x_data.apply(remove_stopwords_spacy)

In [26]:
x_data_new

0      fluxon gaming console pro fast charging blueto...
1      fluxon laptop se expandable storage premium al...
2      acme gaming console lite expandable storage fa...
3      nova woman short formal style black denim rela...
4      bytelabs gaming console lite expandable storag...
                             ...
995    bytelabs unisex legging style gray polyester b...
996    zenco camera se face unlock design warranty id...
997    bytelabs headphone model design lightweight du...
998    lumina woman jean streetwear style beige linen...
999    orion kid short style green denim lightweight ...
Name: description, Length: 1000, dtype: str

In [27]:
import numpy as np
def doc_vector_safe(text: str):
    doc = nlp(str(text))                 # nlp(x)
    if doc.vector_norm:                  # doc has a non-zero vector
        return doc.vector

X_vec = np.vstack(x_data_new.apply(doc_vector_safe).to_numpy())
print("Embeddings shape:", X_vec.shape)  # -> (n_samples, 300) for _md

Embeddings shape: (1000, 300)

In [28]:
X_vec

array([[-0.19910993,  0.04451767,  0.01015929, ..., -0.04420336,
        -0.05157991,  0.2997415 ],
       [-0.1511385 ,  0.08160599,  0.120365  , ..., -0.16165969,
        -0.02887589,  0.17576103],
       [-0.07525119,  0.09409747,  0.1728429 , ..., -0.08666436,
        -0.16045465,  0.20410848],
       ...,
       [-0.06892764,  0.17980276,  0.01167607, ..., -0.06006945,
         0.14632365,  0.21170226],
       [ 0.21463993,  0.11928577, -0.05262299, ...,  0.07869915,
         0.06597746, -0.15698299],
       [ 0.09776845,  0.17436774, -0.17340608, ...,  0.02990758,
         0.19680642,  0.11386966]], shape=(1000, 300), dtype=float32)

In [29]:
Y

0      Electronics
1      Electronics
2      Electronics
3         Clothing
4      Electronics
          ...
995       Clothing
996    Electronics
997    Electronics
998       Clothing
999       Clothing
Name: product_category, Length: 1000, dtype: str

In [30]:
Y_new = Y.map({'Electronics':0,'Clothing':1})

In [31]:
Y_new

0      0
1      0
2      0
3      1
4      0
      ..
995    1
996    0
997    0
998    1
999    1
Name: product_category, Length: 1000, dtype: int64

In [33]:
!python3 -m pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
Xtr, Xte, ytr, yte = train_test_split(X_vec, Y_new, test_size=0.2, random_state=42)
clf = LogisticRegression(max_iter=2000).fit(Xtr, ytr)
print("Accuracy:", clf.score(Xte, yte))

Accuracy: 1.0

In [35]:
predictions = clf.predict(Xte)

In [36]:
predictions

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0])