In [2]:
!python3 -m pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)
Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
data = pd.read_csv("products.csv")

In [4]:
data.head(3)

  product_category                                        description
0      Electronics  Fluxon gaming console (Pro) with fast charging...
1      Electronics  Fluxon laptop (SE) with expandable storage, no...
2      Electronics  Acme gaming console (Lite) with expandable sto...

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  1000 non-null   str
 1   description       1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [7]:
data.shape

(1000, 2)

In [8]:
data.columns

Index(['product_category', 'description'], dtype='str')

In [12]:
data.nunique

<bound method DataFrame.nunique of     product_category                                        description
0        Electronics  Fluxon gaming console (Pro) with fast charging...
1        Electronics  Fluxon laptop (SE) with expandable storage, no...
2        Electronics  Acme gaming console (Lite) with expandable sto...
3           Clothing  Nova women's shorts, formal style in black, de...
4        Electronics  ByteLabs gaming console (Lite) with expandable...
..               ...                                                ...
995         Clothing  ByteLabs unisex leggings, office‑ready style i...
996      Electronics  ZenCo camera (SE) with face unlock, water‑resi...
997      Electronics  ByteLabs headphones (2024 model) with water‑re...
998         Clothing  Lumina women's jeans, streetwear style in beig...
999         Clothing  Orion kids shorts, office‑ready style in green...

[1000 rows x 2 columns]>

In [13]:
!python3 -m pip install spacy

Collecting spacy
  Using cached spacy-3.8.14-cp311-cp311-macosx_11_0_arm64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.15-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.13-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.7 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.13-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Using cached thinc-8.3.13-cp311-cp311-macosx_11_0_arm64.whl.metadata (14 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Using cached srsly-2.5.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Using cached weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Using cached confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Using cached typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: numpy>=1.19.0 in ./venv/lib/python3.11/site-packages (from spacy) (2.4.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from spacy) (2.34.2)
Collecting pydantic<3.0.0,>=2.0.0 (from spacy)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from spacy) (26.2)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached pydantic_core-2.46.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in ./venv/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Using cached blis-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.5 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached smart_open-8.0.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: httpx>=0.24.0 in ./venv/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in ./venv/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.2)
Requirement already satisfied: httpcore==1.* in ./venv/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./venv/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Using cached wrapt-2.2.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.4 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->spacy) (3.0.3)
Using cached spacy-3.8.14-cp311-cp311-macosx_11_0_arm64.whl (6.4 MB)
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached confection-1.3.3-py3-none-any.whl (35 kB)
Using cached cymem-2.0.13-cp311-cp311-macosx_11_0_arm64.whl (43 kB)
Using cached murmurhash-1.0.15-cp311-cp311-macosx_11_0_arm64.whl (27 kB)
Using cached preshed-3.0.13-cp311-cp311-macosx_11_0_arm64.whl (137 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp311-cp311-macosx_11_0_arm64.whl (1.9 MB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Using cached srsly-2.5.3-cp311-cp311-macosx_11_0_arm64.whl (657 kB)
Using cached thinc-8.3.13-cp311-cp311-macosx_11_0_arm64.whl (812 kB)
Using cached blis-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (1.2 MB)
Using cached tqdm-4.68.4-py3-none-any.whl (676 kB)
Using cached typer-0.26.8-py3-none-any.whl (122 kB)
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-1.0.0-py3-none-any.whl (50 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached cloudpathlib-0.24.0-py3-none-any.whl (63 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached smart_open-8.0.0-py3-none-any.whl (73 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached wrapt-2.2.2-cp311-cp311-macosx_11_0_arm64.whl (81 kB)
Installing collected packages: wrapt, wasabi, typing-inspection, tqdm, spacy-loggers, spacy-legacy, shellingham, pydantic-core, murmurhash, mdurl, cymem, confection, cloudpathlib, catalogue, blis, annotated-types, annotated-doc, srsly, smart-open, pydantic, preshed, markdown-it-py, thinc, rich, typer, weasel, spacy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27/27 [spacy]m26/27 [spacy]]c]
Successfully installed annotated-doc-0.0.4 annotated-types-0.7.0 blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.24.0 confection-1.3.3 cymem-2.0.13 markdown-it-py-4.2.0 mdurl-0.1.2 murmurhash-1.0.15 preshed-3.0.13 pydantic-2.13.4 pydantic-core-2.46.4 rich-15.0.0 shellingham-1.5.4 smart-open-8.0.0 spacy-3.8.14 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.3 thinc-8.3.13 tqdm-4.68.4 typer-0.26.8 typing-inspection-0.4.2 wasabi-1.1.3 weasel-1.0.0 wrapt-2.2.2

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [14]:
import spacy

ModuleNotFoundError: No module named 'click'

In [16]:
!python3 -m pip install click

Collecting click
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Installing collected packages: click
Successfully installed click-8.4.2

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [17]:
import spacy

In [19]:
!python3 -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 32.2 MB/s  0:00:13:00:0100:01
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [20]:
nlp = spacy.load("en_core_web_lg")

In [21]:
data.head(3)

  product_category                                        description
0      Electronics  Fluxon gaming console (Pro) with fast charging...
1      Electronics  Fluxon laptop (SE) with expandable storage, no...
2      Electronics  Acme gaming console (Lite) with expandable sto...

In [22]:
X = data['description']
Y = data['product_category']

In [23]:
X.info()

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: description
Non-Null Count  Dtype
--------------  -----
1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB

In [24]:
Y.info()

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: product_category
Non-Null Count  Dtype
--------------  -----
1000 non-null   str
dtypes: str(1)
memory usage: 7.9 KB

In [25]:
type(X)

pandas.Series

In [26]:
type(Y)

pandas.Series

In [30]:
def lemmatize(text):
    doc = nlp(text)
    lemma_text = [token.lemma_.lower() for token in doc]
    return " ".join(lemma_text)

In [33]:
x_data = X.apply(lemmatize).astype("string")

In [34]:
x_data

0      fluxon gaming console ( pro ) with fast chargi...
1      fluxon laptop ( se ) with expandable storage ,...
2      acme gaming console ( lite ) with expandable s...
3      nova woman 's short , formal style in black , ...
4      bytelabs gaming console ( lite ) with expandab...
                             ...
995    bytelabs unisex legging , office‑ready style i...
996    zenco camera ( se ) with face unlock , water‑r...
997    bytelabs headphone ( 2024 model ) with water‑r...
998    lumina woman 's jean , streetwear style in bei...
999    orion kid short , office‑ready style in green ...
Name: description, Length: 1000, dtype: string

In [ ]:
X