In [1]:
!python3 -m pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data.csv")

In [4]:
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
4,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4270 entries, 0 to 4269
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4270 non-null   int64
 1    no_of_dependents          4270 non-null   int64
 2    education                 4270 non-null   str
 3    self_employed             4270 non-null   str
 4    income_annum              4270 non-null   int64
 5    loan_amount               4270 non-null   int64
 6    loan_term                 4270 non-null   int64
 7    credit_score              4266 non-null   float64
 8    residential_assets_value  4270 non-null   int64
 9    commercial_assets_value   4270 non-null   int64
 10   luxury_assets_value       4270 non-null   int64
 11   bank_asset_value          4270 non-null   int64
 12   loan_status               4270 non-null   str
dtypes: float64(1), int64(9), str(3)
memory usage: 433.8 KB

In [6]:
data.shape

(4270, 13)

In [7]:
data.nunique()

loan_id                      4269
 no_of_dependents               6
 education                      2
 self_employed                  2
 income_annum                  98
 loan_amount                  378
 loan_term                     10
 credit_score                 601
 residential_assets_value     278
 commercial_assets_value      188
 luxury_assets_value          379
 bank_asset_value             146
 loan_status                    2
dtype: int64

In [8]:
data.duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
4265    False
4266    False
4267    False
4268    False
4269    False
Length: 4270, dtype: bool

In [9]:
data.duplicated().sum()

np.int64(1)

In [10]:
data_new = data.drop_duplicates(keep='first').reset_index(drop=True)

In [11]:
data_new.duplicated().sum()

np.int64(0)

In [12]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382.0,12400000,8200000,29400000,5000000,Rejected

In [13]:
data_new.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' credit_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='str')

In [15]:
data_new[' loan_amount']

0       29900000
1       12200000
2       29700000
3       30700000
4       24200000
          ...
4264     2300000
4265    11300000
4266    23900000
4267    12800000
4268    29700000
Name:  loan_amount, Length: 4269, dtype: int64

In [16]:
 data_new.columns = [i.strip() for i in data_new.columns]

In [17]:
data_new.columns

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'credit_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='str')

In [18]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382.0,12400000,8200000,29400000,5000000,Rejected

In [19]:
data_new.shape

(4269, 13)

In [20]:
data_new['total_asset_value'] = data_new['residential_assets_value'] + data_new['commercial_assets_value'] + data_new['luxury_assets_value'] + data_new['bank_asset_value']

In [21]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,total_asset_value
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved,50700000
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected,17000000
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected,57700000
3,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected,52700000
4,5,5,Not Graduate,Yes,9800000,24200000,20,382.0,12400000,8200000,29400000,5000000,Rejected,55000000

In [22]:
data_new.drop(columns=['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'],inplace=True)

In [23]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,Graduate,No,9600000,29900000,12,778.0,Approved,50700000
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,Rejected,17000000
2,3,3,Graduate,No,9100000,29700000,20,506.0,Rejected,57700000
3,4,3,Graduate,No,8200000,30700000,8,467.0,Rejected,52700000
4,5,5,Not Graduate,Yes,9800000,24200000,20,382.0,Rejected,55000000

In [25]:
data_new.dtypes

loan_id                int64
no_of_dependents       int64
education                str
self_employed            str
income_annum           int64
loan_amount            int64
loan_term              int64
credit_score         float64
loan_status              str
total_asset_value      int64
dtype: object

In [28]:
!python3 -m pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
le = LabelEncoder()

In [31]:
data_new['education'] = le.fit_transform(data_new['education'])

In [32]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,0,No,9600000,29900000,12,778.0,Approved,50700000
1,2,0,1,Yes,4100000,12200000,8,417.0,Rejected,17000000
2,3,3,0,No,9100000,29700000,20,506.0,Rejected,57700000
3,4,3,0,No,8200000,30700000,8,467.0,Rejected,52700000
4,5,5,1,Yes,9800000,24200000,20,382.0,Rejected,55000000

In [33]:
data_new['self_employed'] = le.fit_transform(data_new['self_employed'])
data_new['loan_status'] = le.fit_transform(data_new['loan_status'])

In [34]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,0,0,9600000,29900000,12,778.0,0,50700000
1,2,0,1,1,4100000,12200000,8,417.0,1,17000000
2,3,3,0,0,9100000,29700000,20,506.0,1,57700000
3,4,3,0,0,8200000,30700000,8,467.0,1,52700000
4,5,5,1,1,9800000,24200000,20,382.0,1,55000000

In [35]:
data_new.shape

(4269, 10)

In [36]:
data_new.isnull().values.any()

np.True_

In [37]:
data_new.isnull().sum()

loan_id              0
no_of_dependents     0
education            0
self_employed        0
income_annum         0
loan_amount          0
loan_term            0
credit_score         4
loan_status          0
total_asset_value    0
dtype: int64

In [39]:
data_new['credit_score'] = data_new['credit_score'].fillna(data_new['credit_score'].mean())

In [40]:
data_new.isnull().sum()

loan_id              0
no_of_dependents     0
education            0
self_employed        0
income_annum         0
loan_amount          0
loan_term            0
credit_score         0
loan_status          0
total_asset_value    0
dtype: int64

In [41]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,0,0,9600000,29900000,12,778.0,0,50700000
1,2,0,1,1,4100000,12200000,8,417.0,1,17000000
2,3,3,0,0,9100000,29700000,20,506.0,1,57700000
3,4,3,0,0,8200000,30700000,8,467.0,1,52700000
4,5,5,1,1,9800000,24200000,20,382.0,1,55000000

In [42]:
!python3 -m pip install numpy

Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (2.4.6)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [43]:
import numpy as np

In [44]:
data_new['income_annum'] = np.log(data_new['income_annum'])

In [45]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,0,0,16.077274,29900000,12,778.0,0,50700000
1,2,0,1,1,15.226498,12200000,8,417.0,1,17000000
2,3,3,0,0,16.023785,29700000,20,506.0,1,57700000
3,4,3,0,0,15.919645,30700000,8,467.0,1,52700000
4,5,5,1,1,16.097893,24200000,20,382.0,1,55000000

In [46]:
data_new['loan_amount'] = np.log(data_new['loan_amount'])
data_new['total_asset_value'] = np.log(data_new['total_asset_value'])

In [47]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_asset_value
0,1,2,0,0,16.077274,17.213369,12,778.0,0,17.741436
1,2,0,1,1,15.226498,16.316947,8,417.0,1,16.648724
2,3,3,0,0,16.023785,17.206658,20,506.0,1,17.870768
3,4,3,0,0,15.919645,17.239773,8,467.0,1,17.780126
4,5,5,1,1,16.097893,17.001863,20,382.0,1,17.822844

In [48]:
X = data_new.drop(columns=['loan_status','loan_id'])

In [49]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,total_asset_value
0,2,0,0,16.077274,17.213369,12,778.0,17.741436
1,0,1,1,15.226498,16.316947,8,417.0,16.648724
2,3,0,0,16.023785,17.206658,20,506.0,17.870768
3,3,0,0,15.919645,17.239773,8,467.0,17.780126
4,5,1,1,16.097893,17.001863,20,382.0,17.822844

In [50]:
Y = data_new['loan_status']

In [51]:
Y

0       0
1       1
2       1
3       1
4       1
       ..
4264    1
4265    0
4266    1
4267    0
4268    0
Name: loan_status, Length: 4269, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [53]:
x_train.shape

(3415, 8)

In [54]:
x_test.shape

(854, 8)

In [55]:
from sklearn.linear_model import LogisticRegression
lg_model = LogisticRegression(max_iter=2000, penalty='l2')

In [56]:
model = lg_model.fit(x_train, y_train)

/Users/prreddy/Documents/EDUeki/AIML/AIML04/github/AIML04/ML/classification/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

In [57]:
model

LogisticRegression(max_iter=2000, penalty='l2')

In [58]:
y_pred = model.predict(x_test)

In [59]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])