In [1]:
!python3 -m pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)
Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data.csv")

In [4]:
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
4,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4270 entries, 0 to 4269
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4270 non-null   int64
 1    no_of_dependents          4270 non-null   int64
 2    education                 4270 non-null   str
 3    self_employed             4270 non-null   str
 4    income_annum              4270 non-null   int64
 5    loan_amount               4270 non-null   int64
 6    loan_term                 4270 non-null   int64
 7    credit_score              4266 non-null   float64
 8    residential_assets_value  4270 non-null   int64
 9    commercial_assets_value   4270 non-null   int64
 10   luxury_assets_value       4270 non-null   int64
 11   bank_asset_value          4270 non-null   int64
 12   loan_status               4270 non-null   str
dtypes: float64(1), int64(9), str(3)
memory usage: 433.8 KB

In [6]:
data.shape

(4270, 13)

In [7]:
data.nunique()

loan_id                      4269
 no_of_dependents               6
 education                      2
 self_employed                  2
 income_annum                  98
 loan_amount                  378
 loan_term                     10
 credit_score                 601
 residential_assets_value     278
 commercial_assets_value      188
 luxury_assets_value          379
 bank_asset_value             146
 loan_status                    2
dtype: int64

In [8]:
data.duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
4265    False
4266    False
4267    False
4268    False
4269    False
Length: 4270, dtype: bool

In [9]:
data.duplicated().sum()

np.int64(1)

In [10]:
data_new = data.drop_duplicates(keep='first').reset_index(drop=True)

In [12]:
data_new.duplicated().sum()

np.int64(0)

In [13]:
data_new.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382.0,12400000,8200000,29400000,5000000,Rejected