In [1]:
!python3 -m pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 42.8 MB/s  0:00:00eta 0:00:01
Using cached numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.5

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("house_data.csv")

In [4]:
data.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index,price
0,1360,2,4,18,1,0,5566,1,248990
1,4272,3,4,29,2,2,2909,0,941769
2,3592,1,4,13,2,1,7364,8,378015
3,966,1,4,19,1,0,3581,0,196887
4,4926,2,4,48,1,1,1691,3,1063441

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sqft        1000 non-null   int64
 1   bedrooms    1000 non-null   int64
 2   bathrooms   1000 non-null   int64
 3   age         1000 non-null   int64
 4   floors      1000 non-null   int64
 5   garage      1000 non-null   int64
 6   lot_size    1000 non-null   int64
 7   city_index  1000 non-null   int64
 8   price       1000 non-null   int64
dtypes: int64(9)
memory usage: 70.4 KB

In [6]:
X = data.drop(columns=['price'])

In [7]:
X.head()

   sqft  bedrooms  bathrooms  age  floors  garage  lot_size  city_index
0  1360         2          4   18       1       0      5566           1
1  4272         3          4   29       2       2      2909           0
2  3592         1          4   13       2       1      7364           8
3   966         1          4   19       1       0      3581           0
4  4926         2          4   48       1       1      1691           3

In [8]:
Y = data[['price']]

In [9]:
Y.head()

     price
0   248990
1   941769
2   378015
3   196887
4  1063441

In [10]:
type(X)

pandas.DataFrame

In [11]:
!python3 -m pip install numpy

Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (2.4.6)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [12]:
import numpy as np

In [13]:
X_new = X.to_numpy(dtype=np.float32)

In [14]:
Y_new = Y.to_numpy(dtype=np.float32)

In [16]:
type(X_new)

numpy.ndarray

In [17]:
type(Y_new)

numpy.ndarray

In [18]:
X_new

array([[1.360e+03, 2.000e+00, 4.000e+00, ..., 0.000e+00, 5.566e+03,
        1.000e+00],
       [4.272e+03, 3.000e+00, 4.000e+00, ..., 2.000e+00, 2.909e+03,
        0.000e+00],
       [3.592e+03, 1.000e+00, 4.000e+00, ..., 1.000e+00, 7.364e+03,
        8.000e+00],
       ...,
       [2.606e+03, 4.000e+00, 4.000e+00, ..., 1.000e+00, 1.495e+03,
        0.000e+00],
       [4.723e+03, 5.000e+00, 2.000e+00, ..., 0.000e+00, 3.148e+03,
        9.000e+00],
       [3.268e+03, 4.000e+00, 3.000e+00, ..., 2.000e+00, 1.556e+03,
        2.000e+00]], shape=(1000, 8), dtype=float32)

In [19]:
!python3 -m pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X_new, Y_new, test_size=0.2, random_state=42)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
x_scaler = StandardScaler().fit(x_train)
y_scaler = StandardScaler().fit(y_train)

In [24]:
x_scaler

StandardScaler()

In [34]:
x_train_scaler = x_scaler.transform(x_train).astype(np.float32)
x_test_scaler = x_scaler.transform(x_test).astype(np.float32)
y_train_scaler = y_scaler.transform(y_train).astype(np.float32)
y_test_scaler = y_scaler.transform(y_test).astype(np.float32)

In [35]:
!python3 -m pip install torch

Requirement already satisfied: torch in ./venv/lib/python3.11/site-packages (2.13.0)
Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from torch) (3.32.2)
Requirement already satisfied: typing-extensions>=4.10.0 in ./venv/lib/python3.11/site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in ./venv/lib/python3.11/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./venv/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./venv/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in ./venv/lib/python3.11/site-packages (from torch) (2026.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [36]:
import torch

In [37]:
x_train_tensor = torch.from_numpy(x_train_scaler)

In [38]:
type(x_train_tensor)

torch.Tensor

In [39]:
x_train_tensor

tensor([[-0.6277, -0.6820, -0.4487,  ..., -0.0493, -0.0639, -1.5592],
        [ 0.5632,  1.4300, -1.3241,  ...,  1.1831,  0.6207,  0.4829],
        [ 1.3523, -0.6820, -0.4487,  ...,  1.1831, -1.4758,  1.1635],
        ...,
        [-1.0622,  1.4300,  0.4268,  ..., -0.0493, -1.2117, -1.2188],
        [-0.7579,  0.7260,  0.4268,  ..., -1.2817,  0.7054, -1.2188],
        [-1.1589,  0.7260, -1.3241,  ..., -1.2817, -1.1701,  0.8232]])

In [41]:
x_test_tensor = torch.from_numpy(x_test_scaler)
y_train_tensor = torch.from_numpy(y_train_scaler)
y_test_tensor = torch.from_numpy(y_test_scaler)

In [42]:
import torch.nn as nn

In [64]:
class HousePricePredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(8,1),
        )
        
    def forward(self, x_train_data):
        return self.network(x_train_data)

In [65]:
model = HousePricePredictor()

In [66]:
model

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [67]:
for param in model.parameters():
    print (param)

Parameter containing:
tensor([[ 0.1548, -0.1592,  0.0545, -0.0993,  0.1203, -0.3519, -0.0622, -0.0317]],
       requires_grad=True)
Parameter containing:
tensor([-0.0828], requires_grad=True)

In [68]:
criterion = nn.MSELoss()

In [69]:
import torch.optim as optim

In [70]:
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [71]:
print("y_predictions:", y_predictions)
print("y_train_tensor:", y_train_tensor)

print(type(y_predictions))
print(type(y_train_tensor))

y_predictions: None
y_train_tensor: tensor([[-6.8785e-01],
        [ 8.1758e-01],
        [ 1.7714e+00],
        [ 1.7366e-01],
        [-2.7583e-01],
        [-1.3223e+00],
        [-1.5818e+00],
        [ 1.3501e+00],
        [-1.3041e+00],
        [ 1.0362e+00],
        [-8.8986e-01],
        [-6.6509e-01],
        [-7.9361e-01],
        [ 5.4014e-01],
        [-4.7095e-01],
        [-1.5124e+00],
        [-1.9227e+00],
        [-1.0104e+00],
        [-6.2411e-01],
        [ 6.7587e-01],
        [-1.4465e+00],
        [-8.6895e-01],
        [ 1.5903e-01],
        [-5.8875e-02],
        [-1.0737e+00],
        [-3.5129e-01],
        [ 2.0810e+00],
        [ 1.7609e-02],
        [-7.6795e-01],
        [-1.3468e+00],
        [ 1.2895e+00],
        [-2.5041e-01],
        [-5.9638e-01],
        [-2.2957e-01],
        [-1.3143e+00],
        [ 1.3550e+00],
        [ 2.6295e-01],
        [ 1.2746e+00],
        [-1.6051e+00],
        [-5.2927e-01],
        [-1.2055e+00],
        [-4.5174e-01],
        [-2.6438e-02],
        [ 9.4482e-01],
        [ 2.2560e+00],
        [-9.4156e-01],
        [ 1.5951e-01],
        [-6.8623e-01],
        [ 8.3977e-01],
        [-1.2346e+00],
        [ 1.0344e-01],
        [-8.8446e-01],
        [-3.6856e-01],
        [ 1.4477e+00],
        [ 1.2708e+00],
        [ 2.3628e+00],
        [-1.6357e-01],
        [-1.4231e+00],
        [-5.4506e-01],
        [ 1.4598e+00],
        [ 2.4392e-01],
        [ 1.1541e-01],
        [ 1.0792e+00],
        [-9.6291e-01],
        [-2.6216e-01],
        [-9.7951e-01],
        [ 5.8447e-01],
        [-6.2833e-01],
        [ 6.0450e-01],
        [-1.9355e-02],
        [-1.4295e+00],
        [-5.1806e-01],
        [ 1.3561e+00],
        [-6.0285e-01],
        [-5.8498e-01],
        [-8.8577e-01],
        [ 1.6158e-01],
        [ 1.1675e+00],
        [ 1.3822e+00],
        [ 1.5051e+00],
        [-1.6682e+00],
        [-1.0087e+00],
        [ 9.2823e-01],
        [-1.2209e+00],
        [ 1.1250e+00],
        [ 1.2107e-01],
        [ 1.3778e+00],
        [ 8.0669e-01],
        [ 2.2994e+00],
        [ 3.6906e-01],
        [ 1.4616e+00],
        [-4.4847e-01],
        [-2.2406e-02],
        [ 8.7283e-01],
        [-8.5983e-01],
        [ 7.7933e-01],
        [-3.2150e-01],
        [ 1.7088e+00],
        [ 1.1502e+00],
        [ 4.9051e-01],
        [ 1.6232e-01],
        [ 1.7232e+00],
        [-8.0331e-01],
        [ 3.5221e-01],
        [-2.8495e-02],
        [ 1.3383e+00],
        [-3.7704e-01],
        [-6.4824e-01],
        [ 9.3623e-01],
        [ 4.1536e-01],
        [-5.2617e-01],
        [-1.4034e+00],
        [ 1.6270e+00],
        [-6.4963e-01],
        [ 6.4120e-01],
        [ 1.0990e+00],
        [-4.9589e-01],
        [-5.9526e-01],
        [-1.7860e+00],
        [ 5.3222e-01],
        [-1.3764e-01],
        [-1.3050e+00],
        [-9.6709e-01],
        [ 8.6724e-01],
        [ 8.2712e-01],
        [-6.0043e-01],
        [ 1.9040e+00],
        [ 1.2049e+00],
        [-7.1375e-01],
        [-1.1544e+00],
        [-7.3819e-01],
        [-2.0155e-01],
        [ 2.0261e+00],
        [-7.8253e-02],
        [-9.5977e-01],
        [ 4.0643e-01],
        [-3.7162e-01],
        [ 7.7796e-01],
        [ 1.2751e+00],
        [-2.9764e-01],
        [-1.1542e+00],
        [-1.5874e+00],
        [ 1.5120e+00],
        [ 1.6765e-01],
        [ 5.2266e-01],
        [ 3.0397e-01],
        [ 1.0031e+00],
        [ 1.7885e+00],
        [ 9.6248e-01],
        [-6.1534e-01],
        [-3.1317e-01],
        [-7.6684e-01],
        [-1.3778e+00],
        [-1.2627e+00],
        [-1.2200e+00],
        [ 1.5236e+00],
        [-2.7729e-01],
        [ 3.4219e-02],
        [-7.9106e-01],
        [-3.2094e-01],
        [-3.4518e-01],
        [ 3.1992e-01],
        [ 1.1024e-01],
        [ 5.0346e-01],
        [ 7.9553e-01],
        [-7.8462e-01],
        [ 2.9679e+00],
        [-9.1460e-01],
        [ 3.0595e-01],
        [-1.2700e+00],
        [ 2.1320e-01],
        [ 1.0598e+00],
        [-1.7679e-01],
        [ 3.6600e-01],
        [-3.1689e-01],
        [ 5.1342e-02],
        [-8.2964e-01],
        [-8.8187e-01],
        [ 4.1254e-01],
        [-1.3937e+00],
        [-6.1295e-01],
        [ 5.5033e-01],
        [-7.7692e-01],
        [-3.0640e-01],
        [ 9.4314e-03],
        [-9.6438e-01],
        [-8.8079e-01],
        [-3.1451e-02],
        [-1.3221e+00],
        [-2.3108e-01],
        [-1.8657e-02],
        [-2.7755e-01],
        [ 3.2782e-01],
        [-3.4625e-02],
        [-1.1587e+00],
        [-3.0989e-02],
        [-1.1523e+00],
        [-5.5730e-01],
        [-8.4527e-01],
        [-1.0517e-02],
        [-1.2235e+00],
        [ 4.3428e-01],
        [ 2.3162e+00],
        [ 2.2464e-01],
        [ 4.6293e-01],
        [-4.2754e-01],
        [-7.2782e-02],
        [-1.5414e+00],
        [-2.7056e-01],
        [-3.7552e-01],
        [ 7.7292e-01],
        [-6.2642e-01],
        [ 7.2437e-01],
        [-1.5943e+00],
        [-1.5550e+00],
        [-5.4834e-01],
        [ 4.3853e-01],
        [-2.7238e-01],
        [ 2.2612e+00],
        [ 1.5014e+00],
        [-8.6768e-01],
        [-2.7272e-01],
        [-4.5361e-01],
        [-6.2325e-01],
        [-1.1154e+00],
        [ 1.3721e+00],
        [ 2.0885e-01],
        [-5.2735e-02],
        [-3.9988e-01],
        [-4.2510e-01],
        [ 1.3187e+00],
        [-6.1456e-01],
        [ 1.3097e+00],
        [-2.5844e-01],
        [ 7.5156e-01],
        [ 4.0481e-01],
        [-3.4573e-01],
        [ 2.2724e+00],
        [ 2.0490e-01],
        [ 3.7489e-01],
        [ 1.5763e+00],
        [-1.4147e+00],
        [ 4.4747e-01],
        [-6.4671e-01],
        [ 6.1315e-01],
        [-7.9621e-01],
        [ 2.5631e+00],
        [ 4.3543e-01],
        [-1.0993e+00],
        [-1.2796e+00],
        [ 1.4763e+00],
        [ 9.7544e-01],
        [ 1.0733e+00],
        [ 5.7790e-01],
        [-2.0202e+00],
        [-1.3953e-01],
        [ 8.1893e-01],
        [-5.7283e-01],
        [-4.3317e-01],
        [-1.4673e+00],
        [ 2.6089e-01],
        [ 4.4800e-01],
        [ 1.4538e-01],
        [ 3.1641e-01],
        [ 1.1035e+00],
        [-9.4384e-01],
        [ 9.8227e-01],
        [-7.3457e-02],
        [ 4.4256e-01],
        [ 1.0795e+00],
        [-1.1846e+00],
        [-1.0256e+00],
        [ 3.8425e-01],
        [-8.1716e-01],
        [-8.5808e-01],
        [ 1.6407e+00],
        [ 1.3976e+00],
        [ 5.8270e-02],
        [ 2.0593e-01],
        [-6.5712e-01],
        [ 4.6002e-01],
        [ 2.6452e-01],
        [-8.1898e-01],
        [-1.5933e+00],
        [ 2.4881e-01],
        [-7.3792e-01],
        [-4.7921e-01],
        [ 1.2992e+00],
        [ 1.6419e+00],
        [-2.0740e-01],
        [ 4.8953e-01],
        [ 9.8797e-01],
        [ 1.1544e-01],
        [-1.5475e+00],
        [ 4.5079e-01],
        [-2.9775e-01],
        [-5.2461e-02],
        [-1.2850e+00],
        [ 9.1418e-01],
        [-6.4626e-01],
        [-1.3065e+00],
        [-6.4864e-01],
        [ 8.6203e-02],
        [ 6.9702e-01],
        [-5.1126e-01],
        [ 8.1707e-01],
        [-1.5219e+00],
        [-6.2510e-01],
        [ 1.2629e+00],
        [-1.5356e+00],
        [ 9.3783e-01],
        [-8.7203e-01],
        [ 2.3733e-01],
        [ 4.6507e-01],
        [-1.4649e+00],
        [-1.0932e+00],
        [ 7.6787e-01],
        [-1.4614e+00],
        [-1.7645e+00],
        [-6.9136e-01],
        [ 1.1797e-01],
        [-1.4922e+00],
        [-6.1229e-01],
        [ 2.4825e-01],
        [ 7.0641e-01],
        [-1.5510e-01],
        [ 4.3338e-01],
        [-1.0879e-01],
        [-1.2251e+00],
        [ 1.0262e+00],
        [-1.4127e+00],
        [-7.6977e-01],
        [ 7.4918e-01],
        [-8.2861e-01],
        [-2.1484e-01],
        [-1.2140e+00],
        [-5.4662e-01],
        [-1.4267e+00],
        [-1.7588e+00],
        [-1.5518e+00],
        [ 7.9071e-01],
        [-1.8486e+00],
        [-1.8561e-01],
        [-3.3766e-01],
        [-1.2133e-01],
        [ 7.7010e-01],
        [-7.0545e-01],
        [-9.1520e-01],
        [ 2.8642e-01],
        [-7.4699e-01],
        [ 7.9119e-02],
        [ 1.0826e+00],
        [ 2.3189e+00],
        [ 5.4214e-01],
        [ 1.8314e-01],
        [-6.5548e-02],
        [ 3.4458e-01],
        [-8.3196e-01],
        [-6.9186e-01],
        [ 1.0920e+00],
        [ 9.5483e-01],
        [ 4.0605e-01],
        [ 1.9013e+00],
        [-1.0611e+00],
        [-7.5451e-01],
        [-1.1489e+00],
        [-2.4382e-02],
        [-1.1194e-01],
        [-9.7387e-01],
        [ 1.0479e+00],
        [-3.9480e-01],
        [ 3.8753e-01],
        [-9.2393e-01],
        [-8.4601e-01],
        [ 6.4844e-02],
        [ 7.1727e-01],
        [ 1.1153e+00],
        [-4.3104e-01],
        [ 1.4179e+00],
        [ 2.0555e+00],
        [-2.0569e-01],
        [ 2.7911e-01],
        [ 6.7787e-02],
        [ 1.0769e+00],
        [ 1.3650e-01],
        [ 6.2467e-01],
        [ 1.5272e+00],
        [ 1.8731e-01],
        [-2.3534e-01],
        [-8.6340e-01],
        [ 2.3949e-01],
        [ 4.4806e-01],
        [-1.1525e+00],
        [ 1.7109e-01],
        [ 5.7370e-01],
        [ 8.8489e-01],
        [ 9.0385e-01],
        [-5.5322e-01],
        [ 8.3737e-01],
        [-7.6017e-02],
        [-1.6480e+00],
        [ 1.2320e+00],
        [ 2.0276e+00],
        [-6.8760e-01],
        [-8.1191e-01],
        [ 1.2548e-01],
        [ 5.2246e-01],
        [ 3.4364e-01],
        [-3.5146e-01],
        [-9.3621e-01],
        [ 1.1514e+00],
        [-8.0149e-01],
        [-8.5676e-01],
        [ 1.0709e-01],
        [ 4.6607e-01],
        [ 3.8171e-02],
        [ 7.7757e-01],
        [ 3.0824e-01],
        [-5.4909e-01],
        [ 3.0718e-01],
        [ 1.2909e+00],
        [-9.0432e-01],
        [-8.6532e-01],
        [ 6.8193e-01],
        [ 5.0536e-01],
        [-1.7077e+00],
        [-1.6515e+00],
        [-1.0314e+00],
        [ 2.9777e-01],
        [ 1.9139e+00],
        [-1.0718e+00],
        [ 2.9016e-01],
        [ 4.2756e-01],
        [-1.1895e+00],
        [ 8.3741e-01],
        [ 1.2893e+00],
        [ 4.5371e-01],
        [ 6.7926e-01],
        [-1.0260e+00],
        [-1.8242e+00],
        [ 1.7245e+00],
        [ 7.1096e-01],
        [-3.4417e-01],
        [-4.2729e-01],
        [ 1.2839e+00],
        [-1.1447e+00],
        [ 3.3163e-01],
        [ 1.0646e+00],
        [ 8.5654e-01],
        [ 4.7558e-01],
        [-1.3809e+00],
        [-1.5816e+00],
        [ 1.3481e+00],
        [ 5.6817e-01],
        [-1.6635e+00],
        [ 6.3386e-01],
        [ 2.0935e+00],
        [ 2.2491e+00],
        [ 2.6533e+00],
        [ 1.1021e+00],
        [ 1.8008e-01],
        [-1.0368e+00],
        [-1.3317e-01],
        [-5.4965e-01],
        [ 5.0133e-01],
        [-1.7514e+00],
        [-1.7683e+00],
        [-5.1345e-01],
        [-6.5197e-01],
        [ 1.4279e+00],
        [ 4.5132e-01],
        [-1.3676e-01],
        [ 1.0732e+00],
        [-8.4535e-01],
        [-8.9222e-01],
        [-3.9063e-02],
        [-1.2478e+00],
        [ 7.2214e-01],
        [ 3.5445e-01],
        [-3.0007e-01],
        [ 1.8351e+00],
        [-1.4648e+00],
        [-1.4855e-01],
        [-1.6268e+00],
        [ 3.2285e-01],
        [-1.1958e+00],
        [-9.7586e-01],
        [-8.6591e-02],
        [ 1.3423e+00],
        [ 4.2530e-01],
        [ 8.9223e-01],
        [-1.3912e+00],
        [-6.0231e-01],
        [ 3.9483e-01],
        [-7.5645e-01],
        [-1.3258e+00],
        [-1.8140e-01],
        [ 1.9947e-01],
        [ 4.4835e-01],
        [ 1.6840e+00],
        [-1.2942e+00],
        [-1.1198e+00],
        [ 1.9322e-01],
        [-9.3540e-01],
        [ 1.7274e+00],
        [-1.4243e-02],
        [-5.0163e-01],
        [ 3.6378e-01],
        [ 6.4414e-01],
        [-7.5310e-01],
        [-1.5202e+00],
        [ 9.3702e-01],
        [ 3.7208e-02],
        [ 9.6759e-01],
        [-4.2786e-01],
        [-3.9479e-03],
        [-3.4617e-01],
        [-1.1854e-01],
        [-5.8148e-01],
        [-2.9966e-02],
        [-2.6114e-01],
        [ 1.1454e+00],
        [-3.5209e-01],
        [ 1.1454e+00],
        [-7.6003e-01],
        [ 1.3360e+00],
        [-9.2057e-01],
        [-8.3018e-01],
        [-4.8823e-01],
        [-1.6683e+00],
        [-6.0629e-01],
        [ 8.3543e-01],
        [ 1.9311e-02],
        [ 1.5582e-01],
        [ 2.4630e+00],
        [ 7.0687e-01],
        [ 1.5974e-01],
        [-7.1817e-01],
        [ 3.2950e-01],
        [-7.5888e-01],
        [-8.7531e-01],
        [ 2.3028e+00],
        [ 6.9484e-01],
        [ 1.4227e+00],
        [ 1.2529e+00],
        [ 8.1108e-01],
        [ 9.4569e-02],
        [-1.7134e+00],
        [ 2.4494e+00],
        [-1.4221e+00],
        [ 1.7604e+00],
        [ 1.1484e+00],
        [-6.5118e-01],
        [-3.2975e-01],
        [-1.2374e+00],
        [-5.5281e-01],
        [ 1.3288e-01],
        [-1.4685e-01],
        [ 8.2307e-01],
        [ 2.7413e-01],
        [ 2.0405e-01],
        [-4.0736e-01],
        [ 1.1857e-01],
        [-4.5274e-02],
        [-2.7328e-01],
        [-1.2705e+00],
        [-6.1455e-02],
        [-8.5413e-01],
        [-8.4874e-01],
        [ 6.8758e-01],
        [-5.1149e-01],
        [ 1.8355e-01],
        [ 1.4937e+00],
        [ 2.4580e-01],
        [-1.8871e-01],
        [-5.4512e-01],
        [ 2.1929e-01],
        [ 7.4607e-01],
        [-1.3411e+00],
        [ 3.0469e-01],
        [-4.0358e-01],
        [-8.7137e-01],
        [-1.5313e+00],
        [-1.3808e+00],
        [-1.3842e+00],
        [-9.2571e-01],
        [ 1.4497e+00],
        [ 7.8259e-01],
        [-3.5670e-01],
        [-2.7366e-01],
        [-1.2927e+00],
        [ 3.9705e-01],
        [ 1.2152e-02],
        [-3.7541e-01],
        [-8.2467e-01],
        [ 1.5700e-01],
        [-3.0622e-01],
        [-2.8990e-01],
        [-2.9513e-01],
        [ 1.5826e+00],
        [-1.8934e+00],
        [ 2.4099e-01],
        [ 8.9053e-01],
        [-7.1179e-01],
        [-1.1230e+00],
        [ 1.0918e+00],
        [-5.9245e-01],
        [ 9.0256e-01],
        [ 1.1322e+00],
        [-7.3702e-02],
        [ 2.1916e-01],
        [-8.2943e-01],
        [ 5.5075e-01],
        [ 8.0737e-02],
        [-4.7626e-01],
        [ 8.0879e-01],
        [-5.5924e-01],
        [ 1.4118e+00],
        [-1.0340e+00],
        [ 3.0613e-01],
        [-6.3763e-01],
        [ 2.4257e+00],
        [ 1.4844e+00],
        [ 5.7097e-01],
        [ 6.9323e-01],
        [-1.6048e+00],
        [ 1.4721e+00],
        [ 1.2031e+00],
        [ 4.6212e-01],
        [-3.5509e-01],
        [-2.4165e-02],
        [ 1.5829e+00],
        [ 2.8299e-01],
        [ 7.9910e-01],
        [ 2.8812e+00],
        [-1.0273e+00],
        [-7.0820e-01],
        [-7.8377e-01],
        [ 1.0898e+00],
        [-1.4929e+00],
        [-3.2185e-01],
        [-1.5338e+00],
        [-1.1566e+00],
        [-1.2134e+00],
        [-3.3080e-01],
        [ 6.8210e-01],
        [ 3.6779e-02],
        [-1.0776e+00],
        [ 7.1975e-02],
        [ 1.2473e+00],
        [ 9.2811e-01],
        [ 5.6973e-01],
        [ 2.4858e+00],
        [-3.0616e-01],
        [-3.8230e-01],
        [-7.5039e-01],
        [ 1.8703e+00],
        [-4.2627e-01],
        [ 9.7986e-01],
        [-4.0669e-01],
        [ 7.5028e-01],
        [ 1.3130e+00],
        [-5.4095e-01],
        [ 1.0721e+00],
        [ 6.2728e-01],
        [ 1.5587e+00],
        [-1.8232e+00],
        [ 1.7103e-01],
        [-1.1424e+00],
        [-1.7778e-01],
        [-1.1197e+00],
        [ 8.1419e-01],
        [ 9.4516e-01],
        [-7.8795e-01],
        [ 8.5899e-01],
        [ 2.1377e-02],
        [ 1.6470e+00],
        [-6.2657e-01],
        [ 1.1262e+00],
        [ 3.5733e-01],
        [-6.3269e-01],
        [ 7.8093e-01],
        [-1.1768e+00],
        [ 5.4091e-01],
        [ 1.3357e-01],
        [-1.4598e+00],
        [-1.0174e+00],
        [ 1.5408e+00],
        [-7.0867e-01],
        [-2.8785e-01],
        [ 5.5134e-01],
        [-1.6458e+00],
        [-1.1740e+00],
        [ 1.9526e+00],
        [ 4.1707e-01],
        [ 2.2257e-01],
        [-1.1208e+00],
        [-5.6077e-01],
        [ 1.4655e-01],
        [ 1.7813e-01],
        [-9.2053e-01],
        [-1.3413e+00],
        [-2.8320e-02],
        [ 7.6997e-01],
        [-6.3870e-01],
        [ 1.0778e+00],
        [-1.4035e+00],
        [-9.3536e-01],
        [ 1.1141e-01],
        [-9.7533e-01],
        [ 5.7406e-01],
        [-8.5867e-01],
        [ 1.1779e+00],
        [ 1.4836e+00],
        [-1.1011e+00],
        [ 2.3074e+00],
        [ 1.4786e+00],
        [ 2.0922e+00],
        [ 1.9416e+00],
        [-1.4865e+00],
        [ 1.7480e+00],
        [-1.9445e-02],
        [-1.5401e+00],
        [ 6.5687e-01],
        [ 9.2941e-01],
        [-1.0919e+00],
        [ 1.1012e+00],
        [-3.0235e-01],
        [-1.3863e+00],
        [-1.2368e-01],
        [-1.5452e+00],
        [-6.5362e-01],
        [ 1.1075e+00],
        [ 3.6567e-01],
        [-1.1335e+00],
        [-5.0354e-01],
        [ 2.2702e-01],
        [ 4.8914e-01],
        [-6.2176e-01],
        [-5.1969e-01],
        [-1.4341e+00],
        [ 1.2679e+00],
        [ 1.5422e+00],
        [-8.9027e-01],
        [ 5.8617e-01],
        [-8.8020e-01],
        [ 2.0043e+00],
        [ 1.0367e+00],
        [-1.9601e+00],
        [ 1.1881e+00],
        [ 4.3426e-01],
        [ 1.2301e+00],
        [ 1.5024e+00],
        [-6.3680e-01],
        [ 1.3165e+00],
        [-6.8409e-01],
        [-6.0340e-01],
        [-1.1548e+00],
        [-8.8481e-01],
        [-2.4152e-03],
        [-7.3978e-01],
        [-6.9602e-01],
        [ 2.9075e-01],
        [ 2.0376e-01],
        [-2.0428e-01],
        [-2.4536e-01],
        [ 5.2952e-01],
        [-4.5996e-01],
        [ 4.4494e-01],
        [ 1.8019e-01],
        [-1.0288e+00],
        [ 4.9922e-01],
        [ 1.1433e+00],
        [ 5.4302e-01],
        [-1.1320e+00],
        [ 6.1769e-01],
        [ 1.2175e+00],
        [-5.3339e-01],
        [ 1.3539e+00],
        [ 2.6965e-01],
        [-5.1403e-01],
        [ 4.3975e-01],
        [-1.7572e+00],
        [ 2.3312e+00],
        [-1.1062e+00],
        [-2.1240e-01],
        [-5.7676e-01],
        [-1.3155e+00],
        [ 1.6100e-01],
        [-1.3169e+00],
        [ 1.2596e-02],
        [ 1.0927e+00],
        [-6.6067e-02],
        [ 9.3824e-01],
        [-1.0720e+00],
        [-1.0220e+00],
        [ 1.2811e+00],
        [-1.3438e+00],
        [-1.3911e+00],
        [-1.1443e+00]])
<class 'NoneType'>
<class 'torch.Tensor'>

In [72]:
model.train()

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [73]:
epochs = 100

In [75]:

for epoch in range(1, epochs + 1):
    y_predictions = model(x_train_tensor)

    loss = criterion(y_predictions, y_train_tensor)
    

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 100, Loss: 0.5502

In [76]:
rows = []
for name, param in model.named_parameters():
    rows.append({
        "Name": name,
        "Shape": tuple(param.shape),
        "Trainable": param.requires_grad,
        "Values (first 5)": [round(v.item(), 4) for v in param.data.flatten()[:5]],
        "Grad (first 5)": None if param.grad is None else [round(g.item(), 4) for g in param.grad.flatten()[:5]]
    })

# Convert to DataFrame for clean display
df = pd.DataFrame(rows)
print(df.to_string(index=False))

            Name  Shape  Trainable                          Values (first 5)                             Grad (first 5)
network.0.weight (1, 8)       True [0.343, -0.0139, 0.0243, -0.0001, 0.0025] [-1.053, -0.0745, -0.0006, -0.004, 0.0131]
  network.0.bias   (1,)       True                                 [-0.0001]                                  [-0.0003]

In [77]:
model.eval()
with torch.no_grad():
    y_pred_test = model(x_test_tensor)
    y_pre_numpy = y_pred_test.numpy()
y_pre_numpy

array([[ 0.35943586],
       [-0.31618217],
       [ 0.57346904],
       [ 0.3906072 ],
       [ 0.46233314],
       [ 0.0621931 ],
       [ 0.27722648],
       [ 0.3203174 ],
       [ 0.07780194],
       [ 0.39726672],
       [ 0.4970964 ],
       [ 0.09387835],
       [-0.3084928 ],
       [ 0.8267204 ],
       [ 0.16791645],
       [-0.73824364],
       [-0.43844482],
       [-0.10487468],
       [ 0.36194703],
       [-0.35473558],
       [ 0.13528502],
       [-0.3821039 ],
       [ 0.33299023],
       [ 0.6368061 ],
       [ 0.01622375],
       [-0.31651515],
       [-0.46497467],
       [-0.42968678],
       [-0.31055656],
       [-0.45844904],
       [-0.6513013 ],
       [ 0.6795034 ],
       [ 0.21946338],
       [-0.18790157],
       [ 0.08303251],
       [ 0.46470076],
       [-0.18663907],
       [-0.03817449],
       [-0.26353258],
       [-0.7983593 ],
       [-0.38591906],
       [-0.30806196],
       [-0.41090402],
       [-0.24708521],
       [ 0.876511  ],
       [ 0.22549994],
       [ 0.04834928],
       [ 0.08194954],
       [ 0.48434654],
       [ 0.2011835 ],
       [-0.52188677],
       [ 0.1288884 ],
       [ 0.48887727],
       [ 0.33605185],
       [ 0.11492109],
       [ 0.02762354],
       [-0.32229865],
       [-0.42932162],
       [ 0.3971928 ],
       [-0.275944  ],
       [ 0.29689732],
       [-0.09164762],
       [-0.4978993 ],
       [-0.16680202],
       [-0.2740284 ],
       [-0.2192672 ],
       [-0.5232429 ],
       [-0.05059221],
       [ 0.6634312 ],
       [ 0.10380325],
       [-0.36565593],
       [ 0.58429354],
       [-0.59536153],
       [ 0.13875909],
       [ 0.07909678],
       [ 0.32935166],
       [ 0.0336631 ],
       [-0.55189496],
       [-0.24742222],
       [ 0.1429349 ],
       [ 0.1441059 ],
       [-0.5713855 ],
       [-0.07112094],
       [-0.71896964],
       [-0.65790004],
       [-0.35716268],
       [ 0.7514581 ],
       [ 0.14662285],
       [-0.1820215 ],
       [-0.83812857],
       [ 0.19565493],
       [ 0.5050908 ],
       [-0.05115984],
       [-0.03652977],
       [ 0.39033446],
       [ 0.35929194],
       [ 0.00130368],
       [ 0.16939613],
       [ 0.53354037],
       [ 0.28307456],
       [ 0.6173027 ],
       [ 0.3190977 ],
       [-0.7899659 ],
       [-0.2520711 ],
       [-0.15401599],
       [ 0.813345  ],
       [-0.09788636],
       [-0.34927312],
       [-0.4397674 ],
       [ 0.54278857],
       [ 0.08194449],
       [-0.37612045],
       [ 0.5468635 ],
       [-0.03535134],
       [ 0.20083745],
       [ 0.69415426],
       [-0.26003006],
       [ 0.20765185],
       [-0.5016039 ],
       [ 0.21054712],
       [-0.5264082 ],
       [ 0.03714318],
       [ 0.29279807],
       [-0.65673906],
       [-0.5603184 ],
       [-0.58413714],
       [-0.15504912],
       [ 0.15627904],
       [ 0.41519314],
       [-0.23962876],
       [ 0.30480963],
       [-0.13747358],
       [ 0.19342864],
       [ 0.40758744],
       [-0.16421436],
       [ 0.32042122],
       [-0.30774194],
       [ 0.09327104],
       [-0.0476905 ],
       [-0.25836477],
       [ 0.02364654],
       [-0.02235926],
       [-0.28874472],
       [ 0.17726219],
       [ 0.37338245],
       [-0.57792383],
       [ 0.4679979 ],
       [-0.55194557],
       [-0.15217364],
       [ 0.5124212 ],
       [-0.08072773],
       [ 0.21792895],
       [ 0.34462315],
       [ 0.37773117],
       [ 0.6080332 ],
       [-0.18624967],
       [-0.5000427 ],
       [ 0.3152643 ],
       [ 0.5772093 ],
       [-0.05666725],
       [-0.39635536],
       [ 0.15597619],
       [ 0.2506601 ],
       [ 0.11353967],
       [ 0.78027135],
       [ 0.25469348],
       [ 0.6268247 ],
       [-0.8029098 ],
       [ 0.03995854],
       [ 0.2693186 ],
       [ 0.22711408],
       [-0.4630964 ],
       [-0.39980516],
       [ 0.07806342],
       [ 0.05803258],
       [-0.13344339],
       [ 0.28808972],
       [ 0.31953594],
       [-0.11207374],
       [-0.28966838],
       [ 0.28910723],
       [ 0.5393611 ],
       [-0.21264173],
       [-0.03775046],
       [-0.2470594 ],
       [-0.4660778 ],
       [ 0.01422852],
       [-0.29472968],
       [ 0.00729889],
       [-0.572015  ],
       [-0.2938269 ],
       [-0.08773938],
       [ 0.7121909 ],
       [ 0.28975332],
       [-0.74833304],
       [ 0.4821296 ],
       [-0.3170403 ],
       [ 0.49380225],
       [-0.25034642],
       [ 0.35902447]], dtype=float32)

In [80]:
y_pred_test = y_scaler.inverse_transform(y_pre_numpy).flatten()
y_pred_test

array([528721.7 , 385460.28, 574106.4 , 535331.44, 550540.56, 465692.88,
       511289.6 , 520426.8 , 469002.62, 536743.5 , 557911.94, 472411.56,
       387090.78, 627807.  , 488110.97, 295964.28, 359535.12, 430266.97,
       529254.2 , 377285.22, 481191.62, 371481.9 , 523114.03, 587536.6 ,
       455945.28, 385389.7 , 353909.6 , 361392.2 , 386653.2 , 355293.3 ,
       314399.94, 596590.4 , 499041.22, 412661.53, 470111.75, 551042.56,
       412929.25, 444410.4 , 396624.38, 283217.06, 370672.94, 387182.12,
       365375.  , 400111.94, 638364.9 , 500321.25, 462757.34, 469882.12,
       555208.4 , 495165.06, 341841.66, 479835.25, 556169.06, 523763.22,
       476873.56, 458362.56, 384163.3 , 361469.62, 536727.9 , 393992.6 ,
       515460.72, 433071.72, 346928.1 , 417135.6 , 394398.78, 406010.62,
       341554.1 , 441777.3 , 593182.4 , 474516.1 , 374969.62, 576401.6 ,
       326261.72, 481928.28, 469277.2 , 522342.5 , 459643.22, 335478.56,
       400040.5 , 482813.75, 483062.06, 331345.7 , 437424.28, 300051.25,
       313000.75, 376770.56, 611848.  , 483595.75, 413908.38, 274784.2 ,
       493992.78, 559607.06, 441656.94, 444759.16, 535273.56, 528691.2 ,
       452781.56, 488424.72, 565639.7 , 512529.66, 583401.06, 520168.2 ,
       284996.8 , 399054.72, 419846.8 , 624970.9 , 431748.8 , 378443.5 ,
       359254.66, 567600.7 , 469881.03, 372750.7 , 568464.75, 445009.06,
       495091.7 , 599697.06, 397367.06, 496536.66, 346142.53, 497150.6 ,
       340882.9 , 460381.16, 514591.5 , 313246.9 , 333692.44, 328641.78,
       419627.75, 485643.3 , 540544.75, 401693.06, 517138.47, 423354.53,
       493520.7 , 538932.  , 417684.3 , 520448.84, 387250.  , 472282.78,
       442392.6 , 397720.2 , 457519.25, 447763.97, 391278.25, 490092.7 ,
       531679.  , 329959.28, 551741.75, 335467.84, 420237.47, 561161.44,
       435387.22, 498715.88, 525580.75, 532601.1 , 581435.5 , 413011.8 ,
       346473.6 , 519355.34, 574899.44, 440489.12, 368459.97, 485579.1 ,
       505656.34, 476580.62, 617957.75, 506511.6 , 585420.1 , 282252.12,
       460978.12, 509612.78, 500663.53, 354307.88, 367728.44, 469058.1 ,
       464810.66, 424209.12, 513593.1 , 520261.12, 428740.44, 391082.4 ,
       513808.88, 566873.94, 407415.5 , 444500.34, 400117.44, 353675.7 ,
       455522.22, 390009.2 , 454052.8 , 331212.22, 390200.62, 433900.44,
       603521.6 , 513945.88, 293824.88, 554738.25, 385278.3 , 557213.4 ,
       399420.44, 528634.44], dtype=float32)

In [81]:
torch.save(model.state_dict(), 'house.pth')