In [1]:
!python3 -m pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.11/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("house_data.csv")

In [4]:
data.head()

,sqft,bedrooms,bathrooms,age,floors,garage,lot_size,city_index,price
0,1360,2,4,18,1,0,5566,1,248990
1,4272,3,4,29,2,2,2909,0,941769
2,3592,1,4,13,2,1,7364,8,378015
3,966,1,4,19,1,0,3581,0,196887
4,4926,2,4,48,1,1,1691,3,1063441

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sqft        1000 non-null   int64
 1   bedrooms    1000 non-null   int64
 2   bathrooms   1000 non-null   int64
 3   age         1000 non-null   int64
 4   floors      1000 non-null   int64
 5   garage      1000 non-null   int64
 6   lot_size    1000 non-null   int64
 7   city_index  1000 non-null   int64
 8   price       1000 non-null   int64
dtypes: int64(9)
memory usage: 70.4 KB

In [6]:
X = data.drop(columns=['price'])

In [7]:
X.head()

   sqft  bedrooms  bathrooms  age  floors  garage  lot_size  city_index
0  1360         2          4   18       1       0      5566           1
1  4272         3          4   29       2       2      2909           0
2  3592         1          4   13       2       1      7364           8
3   966         1          4   19       1       0      3581           0
4  4926         2          4   48       1       1      1691           3

In [8]:
Y = data[['price']]

In [9]:
Y.head()

     price
0   248990
1   941769
2   378015
3   196887
4  1063441

In [10]:
type(X)

pandas.DataFrame

In [11]:
!python3 -m pip install numpy

Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (2.4.6)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [12]:
import numpy as np

In [13]:
X_new = X.to_numpy(dtype=np.float32)

In [14]:
Y_new = Y.to_numpy(dtype=np.float32)

In [15]:
type(X_new)

numpy.ndarray

In [16]:
type(Y_new)

numpy.ndarray

In [17]:
X_new

array([[1.360e+03, 2.000e+00, 4.000e+00, ..., 0.000e+00, 5.566e+03,
        1.000e+00],
       [4.272e+03, 3.000e+00, 4.000e+00, ..., 2.000e+00, 2.909e+03,
        0.000e+00],
       [3.592e+03, 1.000e+00, 4.000e+00, ..., 1.000e+00, 7.364e+03,
        8.000e+00],
       ...,
       [2.606e+03, 4.000e+00, 4.000e+00, ..., 1.000e+00, 1.495e+03,
        0.000e+00],
       [4.723e+03, 5.000e+00, 2.000e+00, ..., 0.000e+00, 3.148e+03,
        9.000e+00],
       [3.268e+03, 4.000e+00, 3.000e+00, ..., 2.000e+00, 1.556e+03,
        2.000e+00]], shape=(1000, 8), dtype=float32)

In [18]:
!python3 -m pip install scikit-learn

Requirement already satisfied: scikit-learn in ./venv/lib/python3.11/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(X_new, Y_new, test_size=0.2, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
x_scaler = StandardScaler().fit(x_train)
y_scaler = StandardScaler().fit(y_train)

In [23]:
x_scaler

StandardScaler()

In [24]:
x_train_scaler = x_scaler.transform(x_train).astype(np.float32)
x_test_scaler = x_scaler.transform(x_test).astype(np.float32)
y_train_scaler = y_scaler.transform(y_train).astype(np.float32)
y_test_scaler = y_scaler.transform(y_test).astype(np.float32)

In [25]:
!python3 -m pip install torch

Requirement already satisfied: torch in ./venv/lib/python3.11/site-packages (2.13.0)
Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from torch) (3.32.2)
Requirement already satisfied: typing-extensions>=4.10.0 in ./venv/lib/python3.11/site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in ./venv/lib/python3.11/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./venv/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./venv/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in ./venv/lib/python3.11/site-packages (from torch) (2026.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip

In [26]:
import torch

In [27]:
x_train_tensor = torch.from_numpy(x_train_scaler)

In [28]:
type(x_train_tensor)

torch.Tensor

In [29]:
x_train_tensor

tensor([[-0.6277, -0.6820, -0.4487,  ..., -0.0493, -0.0639, -1.5592],
        [ 0.5632,  1.4300, -1.3241,  ...,  1.1831,  0.6207,  0.4829],
        [ 1.3523, -0.6820, -0.4487,  ...,  1.1831, -1.4758,  1.1635],
        ...,
        [-1.0622,  1.4300,  0.4268,  ..., -0.0493, -1.2117, -1.2188],
        [-0.7579,  0.7260,  0.4268,  ..., -1.2817,  0.7054, -1.2188],
        [-1.1589,  0.7260, -1.3241,  ..., -1.2817, -1.1701,  0.8232]])

In [30]:
x_test_tensor = torch.from_numpy(x_test_scaler)
y_train_tensor = torch.from_numpy(y_train_scaler)
y_test_tensor = torch.from_numpy(y_test_scaler)

In [31]:
import torch.nn as nn

In [47]:
class HousePricePredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(8,16),
            nn.ReLU(),
            nn.Linear(16,8),
            nn.ReLU(),
            nn.Linear(8,4),
            nn.ReLU(),
            nn.Linear(4,1)
            
        )
        
    def forward(self, x_train_data):
        return self.network(x_train_data)

In [48]:
model = HousePricePredictor()

In [50]:
model

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=4, bias=True)
    (5): ReLU()
    (6): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [52]:
for param in model.parameters():
    print (param)

Parameter containing:
tensor([[-0.1546, -0.0532,  0.0184, -0.1826, -0.1062,  0.3338,  0.2829,  0.1830],
        [-0.0963,  0.1374, -0.2614,  0.3063, -0.2714, -0.1071, -0.0497, -0.1968],
        [ 0.2602,  0.1939, -0.3524, -0.0215, -0.1785,  0.2960, -0.0477,  0.0601],
        [ 0.2918,  0.0979,  0.1475,  0.2177, -0.1859, -0.2707,  0.0938,  0.2020],
        [-0.2761,  0.0211, -0.1440, -0.0648, -0.2103,  0.2452, -0.2620, -0.0684],
        [ 0.2166,  0.0655,  0.3279, -0.2051,  0.0869, -0.2196,  0.2215,  0.2832],
        [ 0.1263, -0.3106,  0.1727, -0.2905, -0.0517,  0.1369, -0.1918,  0.2546],
        [ 0.2935, -0.3009,  0.0826, -0.3499, -0.0691,  0.2348, -0.2833, -0.0113],
        [-0.1031,  0.2814, -0.2643,  0.3355, -0.2396,  0.3343,  0.0886,  0.0868],
        [-0.0879, -0.0284, -0.1205, -0.1943, -0.2740,  0.2440, -0.0062,  0.0945],
        [ 0.2517, -0.1567,  0.3105, -0.3352, -0.0059, -0.0546,  0.0477, -0.1743],
        [-0.0404, -0.0522, -0.2539,  0.1859, -0.3268,  0.1520,  0.0732,  0.3106],
        [ 0.1140, -0.3495, -0.1309, -0.2585,  0.0497,  0.1579, -0.2581, -0.0962],
        [-0.3216,  0.0449, -0.1764,  0.0706,  0.2309, -0.2643,  0.0074,  0.1741],
        [ 0.0762,  0.2062,  0.1454, -0.2281,  0.1074, -0.0874,  0.1910,  0.1442],
        [ 0.1553, -0.0033, -0.3487,  0.3387,  0.1647,  0.3434, -0.0696, -0.0679]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0977,  0.2579,  0.0490, -0.1219,  0.1870,  0.0253,  0.3340, -0.2816,
         0.1302,  0.3249,  0.1868,  0.1433,  0.3107,  0.1697, -0.1780,  0.0539],
       requires_grad=True)
Parameter containing:
tensor([[-0.2315,  0.0205,  0.0929, -0.0878,  0.2253,  0.2219,  0.1945,  0.2048,
         -0.0744, -0.2423,  0.1746,  0.0483,  0.0703, -0.1970,  0.0783, -0.0879],
        [-0.0838, -0.0762,  0.2116,  0.1359, -0.2389,  0.1947,  0.1226,  0.1994,
         -0.1961, -0.0165,  0.1359,  0.1134, -0.0339, -0.0745, -0.0444,  0.1629],
        [ 0.2113, -0.1253, -0.0401,  0.2116, -0.0594,  0.1291, -0.0149, -0.2309,
          0.1324, -0.2016,  0.1144, -0.1843, -0.0682,  0.1860,  0.0181,  0.0859],
        [-0.0778, -0.0889, -0.1166, -0.0390, -0.1031,  0.2478, -0.0906, -0.2293,
          0.0386,  0.1486, -0.0464, -0.0167, -0.2098, -0.2021, -0.0180, -0.0856],
        [ 0.0824,  0.1871,  0.1393, -0.2122,  0.1835,  0.0253, -0.0159,  0.1275,
          0.2187,  0.1706,  0.0351, -0.0401,  0.1883,  0.1424,  0.1132,  0.1890],
        [ 0.1262,  0.0943,  0.0500,  0.0670, -0.0083, -0.0997, -0.2254,  0.1100,
         -0.1403,  0.0750,  0.2237,  0.1467, -0.2197,  0.0104,  0.1971, -0.1779],
        [-0.0432, -0.1882, -0.0511, -0.2356,  0.1383,  0.0908, -0.1436, -0.0263,
          0.0042, -0.2255, -0.0125, -0.1536, -0.1936, -0.1297,  0.2386, -0.2087],
        [ 0.1290, -0.0948,  0.0926, -0.1228,  0.1073,  0.1780, -0.0212,  0.2251,
          0.1532,  0.0903, -0.2393, -0.0653, -0.2217,  0.1113, -0.1029,  0.1889]],
       requires_grad=True)
Parameter containing:
tensor([-0.1278,  0.1736, -0.0051,  0.2321,  0.1807, -0.0367, -0.0047, -0.0309],
       requires_grad=True)
Parameter containing:
tensor([[-0.0060, -0.0332,  0.1242, -0.1373,  0.2379, -0.1631, -0.3183,  0.3494],
        [ 0.1960,  0.2696, -0.1922,  0.2346, -0.0477, -0.0764,  0.0290,  0.1587],
        [-0.1913, -0.0615,  0.1954,  0.0984, -0.2814,  0.2123,  0.2124,  0.1765],
        [ 0.1988, -0.0542,  0.3429,  0.1289, -0.1232, -0.0241, -0.0798, -0.2587]],
       requires_grad=True)
Parameter containing:
tensor([-0.3027,  0.2823,  0.2752,  0.0713], requires_grad=True)
Parameter containing:
tensor([[-0.2860,  0.1082,  0.0984, -0.3811]], requires_grad=True)
Parameter containing:
tensor([-0.4389], requires_grad=True)

In [53]:
criterion = nn.MSELoss()

In [54]:
import torch.optim as optim

In [55]:
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [56]:
model.train()

HousePricePredictor(
  (network): Sequential(
    (0): Linear(in_features=8, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=4, bias=True)
    (5): ReLU()
    (6): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [57]:
epochs = 100

In [59]:

for epoch in range(1, epochs + 1):
    y_predictions = model(x_train_tensor)

    loss = criterion(y_predictions, y_train_tensor)
    

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 100, Loss: 0.2306

In [60]:
rows = []
for name, param in model.named_parameters():
    rows.append({
        "Name": name,
        "Shape": tuple(param.shape),
        "Trainable": param.requires_grad,
        "Values (first 5)": [round(v.item(), 4) for v in param.data.flatten()[:5]],
        "Grad (first 5)": None if param.grad is None else [round(g.item(), 4) for g in param.grad.flatten()[:5]]
    })

# Convert to DataFrame for clean display
df = pd.DataFrame(rows)
print(df.to_string(index=False))

            Name   Shape  Trainable                            Values (first 5)                                Grad (first 5)
network.0.weight (16, 8)       True [-0.3592, -0.2994, 0.1481, -0.0911, 0.0625]   [-0.0016, 0.0043, -0.0023, -0.0036, -0.004]
  network.0.bias   (16,)       True     [0.2821, 0.3538, 0.2427, 0.0379, 0.331]   [0.0005, 0.0013, -0.0012, -0.0007, -0.0012]
network.2.weight (8, 16)       True   [-0.2557, 0.0202, 0.2562, 0.0069, 0.1402] [-0.0011, -0.0007, -0.0006, -0.0012, -0.0017]
  network.2.bias    (8,)       True   [-0.0423, 0.2973, 0.0642, 0.3917, 0.2654]  [-0.0024, -0.0047, 0.0003, -0.0035, -0.0006]
network.4.weight  (4, 8)       True [-0.0837, -0.1492, 0.3754, -0.2263, 0.4197]    [0.0005, 0.0055, -0.0054, 0.0007, -0.0109]
  network.4.bias    (4,)       True           [-0.1321, 0.3652, 0.3653, 0.0369]                [0.0008, -0.0005, -0.001, 0.0]
network.6.weight  (1, 4)       True           [-0.4859, 0.2621, 0.286, -0.3532]               [0.0173, -0.0141, -0.0121, 0.0]
  network.6.bias    (1,)       True                                   [-0.3648]                                     [-0.0017]

In [61]:
model.eval()
with torch.no_grad():
    y_pred_test = model(x_test_tensor)
    y_pre_numpy = y_pred_test.numpy()
y_pre_numpy

array([[ 9.71285701e-01],
       [-2.71162570e-01],
       [ 1.13421977e+00],
       [ 1.23473728e+00],
       [ 5.64825058e-01],
       [ 6.97705030e-01],
       [ 1.29729772e+00],
       [ 9.01377559e-01],
       [ 5.49800754e-01],
       [ 9.44987893e-01],
       [ 4.66001779e-01],
       [ 2.55100816e-01],
       [-1.26372564e+00],
       [ 1.48717034e+00],
       [-4.05083954e-01],
       [-1.25671387e+00],
       [-4.13371056e-01],
       [-8.42610836e-01],
       [ 6.37985349e-01],
       [-1.06850982e+00],
       [ 5.08671880e-01],
       [-2.74015129e-01],
       [ 4.85006660e-01],
       [ 6.39315486e-01],
       [-5.49744904e-01],
       [-1.04548323e+00],
       [-3.57577950e-01],
       [-6.34323835e-01],
       [-1.28481150e+00],
       [-7.16689587e-01],
       [-1.31363463e+00],
       [ 1.02505457e+00],
       [ 5.48678279e-01],
       [-9.37489152e-01],
       [-4.12006289e-01],
       [ 5.37941813e-01],
       [-8.50049019e-01],
       [-4.00935382e-01],
       [-1.10519505e+00],
       [-1.27997398e+00],
       [-1.15160656e+00],
       [-1.28325009e+00],
       [-4.20220941e-01],
       [-1.28165627e+00],
       [ 1.59205878e+00],
       [ 1.19318283e+00],
       [ 7.11677551e-01],
       [ 7.27242470e-01],
       [ 1.30936658e+00],
       [ 3.04254860e-01],
       [-1.21038258e+00],
       [ 3.44388098e-01],
       [ 7.95855165e-01],
       [ 7.48546004e-01],
       [-5.77371418e-01],
       [ 7.13422418e-01],
       [-1.29299164e+00],
       [-1.28975570e+00],
       [ 3.25473815e-01],
       [-1.21530485e+00],
       [ 1.11066198e+00],
       [-9.53619242e-01],
       [-1.25243092e+00],
       [-5.33411980e-01],
       [-1.17042065e-02],
       [-1.34181559e-01],
       [-7.35092640e-01],
       [ 4.10434574e-01],
       [ 9.14963365e-01],
       [ 4.43930596e-01],
       [-3.78694832e-01],
       [ 1.12146747e+00],
       [-1.01629341e+00],
       [-2.01418340e-01],
       [ 1.52167588e-01],
       [ 2.98945159e-01],
       [-3.17553699e-01],
       [-1.14434683e+00],
       [-1.73369914e-01],
       [ 1.14817691e+00],
       [-3.90743852e-01],
       [-9.72980976e-01],
       [-5.74575663e-01],
       [-1.30972838e+00],
       [-1.33790183e+00],
       [-1.07523882e+00],
       [ 1.50886643e+00],
       [ 1.13402212e+00],
       [-4.92584467e-01],
       [-1.43588674e+00],
       [ 1.09458864e+00],
       [ 7.35956669e-01],
       [-7.36990452e-01],
       [ 6.14656329e-01],
       [ 2.32470423e-01],
       [ 1.34621358e+00],
       [ 8.45065951e-01],
       [ 8.67081761e-01],
       [ 8.12094092e-01],
       [ 6.90906048e-02],
       [ 9.81725454e-01],
       [ 9.20254588e-01],
       [-1.39933145e+00],
       [-5.85108995e-04],
       [-2.92952180e-01],
       [ 1.25248802e+00],
       [-4.72212285e-01],
       [-1.23868680e+00],
       [-1.29494870e+00],
       [ 1.39091694e+00],
       [ 8.85722518e-01],
       [-8.58881950e-01],
       [ 9.81341004e-01],
       [-3.92464161e-01],
       [ 5.65606952e-01],
       [ 1.12605441e+00],
       [-1.07622135e+00],
       [ 1.03522384e+00],
       [-1.25109935e+00],
       [ 3.95144254e-01],
       [-1.41654432e+00],
       [-4.36347812e-01],
       [ 6.65528059e-01],
       [-1.06312788e+00],
       [-9.43965793e-01],
       [-9.57615376e-01],
       [-4.74200875e-01],
       [ 8.67487788e-01],
       [ 1.07519400e+00],
       [-1.00177467e-01],
       [ 4.14077908e-01],
       [ 3.26254457e-01],
       [-1.67373687e-01],
       [ 4.96740311e-01],
       [ 1.87171191e-01],
       [ 9.53315496e-01],
       [-2.02230603e-01],
       [ 2.91386276e-01],
       [ 2.81282336e-01],
       [-1.13777971e+00],
       [-4.07850385e-01],
       [ 4.73490387e-01],
       [-9.42566395e-01],
       [ 6.68383479e-01],
       [ 8.64234805e-01],
       [-1.04853249e+00],
       [ 1.21858990e+00],
       [-9.02838230e-01],
       [ 2.06011385e-01],
       [ 1.33171034e+00],
       [-8.05500150e-02],
       [ 6.85659528e-01],
       [ 1.10410106e+00],
       [ 1.10542750e+00],
       [ 1.55778468e+00],
       [ 1.63017362e-01],
       [-1.25031614e+00],
       [ 1.56477302e-01],
       [ 1.31299627e+00],
       [ 3.96846980e-01],
       [-1.23206794e+00],
       [ 1.21084201e+00],
       [ 8.55585694e-01],
       [ 4.88041729e-01],
       [ 1.31476367e+00],
       [ 1.32939029e+00],
       [ 9.30001855e-01],
       [-1.38023794e+00],
       [ 9.45161581e-02],
       [ 9.93149042e-01],
       [ 1.58906192e-01],
       [-1.38657451e+00],
       [-6.16943836e-01],
       [-8.80103827e-01],
       [-1.59089506e-01],
       [-5.89247644e-01],
       [ 2.19514936e-01],
       [ 1.30938232e+00],
       [ 3.90266091e-01],
       [-3.16684127e-01],
       [ 1.17187107e+00],
       [ 7.12967515e-01],
       [-1.18505681e+00],
       [-1.78087592e-01],
       [-3.57755423e-02],
       [-5.39813161e-01],
       [-1.00464141e+00],
       [-1.00352168e-01],
       [-8.30013752e-02],
       [-1.13560033e+00],
       [-3.51840466e-01],
       [-4.08540905e-01],
       [ 1.03822911e+00],
       [ 1.13128006e+00],
       [-1.33253527e+00],
       [ 9.09413457e-01],
       [-1.34227216e+00],
       [ 1.43047988e+00],
       [-7.84635365e-01],
       [ 1.09397948e-01]], dtype=float32)

In [62]:
y_pred_test = y_scaler.inverse_transform(y_pre_numpy).flatten()
y_pred_test

array([658461.4 , 395006.47, 693010.75, 714324.94, 572273.44, 600450.  ,
       727590.6 , 643637.7 , 569087.6 , 652885.06, 551318.44, 506597.97,
       184538.47, 767852.1 , 366609.12, 186025.28, 364851.88, 273833.75,
       587786.7 , 225933.  , 560366.44, 394401.6 , 555348.4 , 588068.75,
       335934.5 , 230815.67, 376682.53, 317999.94, 180067.31, 300534.7 ,
       173955.5 , 669862.8 , 568849.6 , 253715.27, 365141.25, 566573.  ,
       272256.5 , 367488.8 , 218154.08, 181093.1 , 208312.75, 180398.4 ,
       363399.38, 180736.38, 790093.2 , 705513.56, 603412.75, 606713.25,
       730149.75, 517020.84, 195849.6 , 525530.9 , 621262.2 , 611230.56,
       330076.44, 603782.75, 178332.75, 179018.9 , 521520.22, 194805.84,
       688015.4 , 250294.97, 186933.44, 339397.8 , 450023.3 , 424052.6 ,
       296632.44, 539535.7 , 646518.5 , 546638.4 , 372204.78, 690306.6 ,
       237005.22, 409795.38, 484771.5 , 515894.94, 385169.47, 209852.14,
       415742.9 , 695970.25, 369649.88, 246189.4 , 330669.25, 174783.81,
       168809.78, 224506.14, 772452.6 , 692968.8 , 348055.06, 148032.56,
       684607.1 , 608561.  , 296230.  , 582839.9 , 501799.3 , 737962.94,
       631697.1 , 636365.44, 624705.6 , 467155.44, 660675.06, 647640.5 ,
       155783.94, 452381.06, 390386.1 , 718088.9 , 352374.88, 189847.81,
       177917.78, 747442.06, 640318.1 , 270383.53, 660593.56, 369285.06,
       572439.25, 691279.3 , 224297.8 , 672019.1 , 187215.81, 536293.5 ,
       152134.03, 359979.75, 593627.  , 227074.2 , 252341.92, 249447.61,
       351953.22, 636451.56, 680494.6 , 431263.  , 540308.25, 521685.75,
       417014.38, 557836.4 , 492193.84, 654650.9 , 409623.16, 514292.12,
       512149.62, 211244.66, 366022.5 , 552906.4 , 252638.66, 594232.5 ,
       635761.75, 230169.1 , 710901.  , 261062.83, 496188.8 , 734887.6 ,
       435424.9 , 597895.75, 686624.2 , 686905.5 , 782825.5 , 487072.12,
       187381.88, 485685.34, 730919.4 , 536654.5 , 191251.31, 709258.06,
       633927.75, 555991.94, 731294.1 , 734395.6 , 649707.4 , 159832.62,
       472546.8 , 663097.4 , 486200.38, 158488.97, 321685.28, 265883.53,
       418771.  , 327558.12, 499052.16, 730153.06, 535259.06, 385353.84,
       700994.5 , 603686.3 , 201219.8 , 414742.56, 444919.1 , 338040.47,
       239475.97, 431225.94, 434905.1 , 211706.78, 377899.12, 365876.06,
       672656.4 , 692387.4 , 169947.72, 645341.7 , 167883.06, 755831.2 ,
       286127.12, 475702.4 ], dtype=float32)

In [63]:
torch.save(model.state_dict(), 'house.pth')